import type { MechanicDefinition, RulesetDefinition, TokenDefinition } from './mechanicTypes';

export const DEFAULT_RULESET_VERSION = 'local-2026-06-13';

const now = 1765584000000;

function mechanic(definition: Omit<MechanicDefinition, 'updatedAt'>): MechanicDefinition {
  return { ...definition, updatedAt: now };
}

function token(definition: Omit<TokenDefinition, 'updatedAt'>): TokenDefinition {
  return { ...definition, updatedAt: now };
}

export const defaultRuleset: RulesetDefinition = {
  version: DEFAULT_RULESET_VERSION,
  publishedAt: now,
  mechanics: {
    firebending: mechanic({
      id: 'firebending',
      name: 'Firebending',
      kind: 'ability_word',
      setCodes: ['TLA'],
      rulesText: 'Avatar set mechanic placeholder: attack-driven red mana automation hook.',
      engineHandler: 'firebending.attackMana.v1',
      eventHooks: ['onAttackDeclared'],
      parameters: { manaColor: 'R' },
      ui: {
        shortLabel: 'Firebend',
        reminder: 'Attack-triggered red mana support is semi-automated.',
        actionLabel: 'Add firebending mana',
      },
      automationLevel: 'semi_automated',
    }),
    airbend: mechanic({
      id: 'airbend',
      name: 'Airbend',
      kind: 'action',
      setCodes: ['TLA'],
      rulesText: 'Avatar set mechanic placeholder: exile a card with a return/cast-for-two style prompt.',
      engineHandler: 'airbend.exileCastForTwo.v1',
      eventHooks: ['onCast', 'onZoneChange'],
      parameters: { returnCostGeneric: 2 },
      ui: {
        shortLabel: 'Airbend',
        reminder: 'Track the exiled object and its return permission.',
      },
      automationLevel: 'manual_prompt',
    }),
    waterbend: mechanic({
      id: 'waterbend',
      name: 'Waterbend',
      kind: 'cost',
      setCodes: ['TLA'],
      rulesText: 'Avatar set mechanic placeholder: alternate payment using tapped lands, creatures, or artifacts.',
      engineHandler: 'waterbend.costPayment.v1',
      eventHooks: ['onCostPayment'],
      parameters: { allowedTapSources: ['Land', 'Creature', 'Artifact'] },
      ui: {
        shortLabel: 'Waterbend',
        reminder: 'Confirm tapped objects used to pay the waterbend cost.',
      },
      automationLevel: 'manual_prompt',
    }),
    earthbend: mechanic({
      id: 'earthbend',
      name: 'Earthbend',
      kind: 'action',
      setCodes: ['TLA'],
      rulesText: 'Avatar set mechanic placeholder: animate land with recovery/haste metadata.',
      engineHandler: 'earthbend.animateLand.v1',
      eventHooks: ['onActivateAbility', 'onZoneChange'],
      parameters: { grantsHaste: true, objectType: 'Land' },
      ui: {
        shortLabel: 'Earthbend',
        reminder: 'Choose a land and track its temporary creature state manually.',
      },
      automationLevel: 'manual_prompt',
    }),
    'double-faced-sagas': mechanic({
      id: 'double-faced-sagas',
      name: 'Double-faced Sagas',
      kind: 'card_frame',
      setCodes: ['TLA'],
      rulesText: 'Metadata for Saga cards with a second face.',
      eventHooks: ['manual'],
      parameters: { usesSagaChapters: true, doubleFaced: true },
      ui: { reminder: 'Use transform controls when the Saga instruction says to transform.' },
      automationLevel: 'metadata_only',
    }),
    lesson: mechanic({
      id: 'lesson',
      name: 'Lesson',
      kind: 'subtype',
      setCodes: ['STX', 'TLA'],
      rulesText: 'Lesson is a spell subtype used by learn and related effects.',
      eventHooks: ['manual'],
      parameters: { subtype: 'Lesson' },
      ui: { badge: 'Lesson' },
      automationLevel: 'metadata_only',
    }),
    exhaust: mechanic({
      id: 'exhaust',
      name: 'Exhaust',
      kind: 'rules_pattern',
      setCodes: ['DFT'],
      rulesText: 'Once-per-object ability tracking hook.',
      engineHandler: 'exhaust.oncePerObject.v1',
      eventHooks: ['onActivateAbility'],
      parameters: { oncePerObject: true },
      ui: { reminder: 'Mark this object after its exhaust ability is used.' },
      automationLevel: 'manual_prompt',
    }),
    clue: mechanic({
      id: 'clue',
      name: 'Clue',
      kind: 'token',
      setCodes: ['SOI', 'MKM', 'TLA'],
      rulesText: 'Artifact token with "{2}, Sacrifice this artifact: Draw a card."',
      engineHandler: 'clue.activatedDraw.v1',
      eventHooks: ['onActivateAbility'],
      parameters: { costGeneric: 2, sacrificeSelf: true, draws: 1 },
      ui: { shortLabel: 'Clue', actionLabel: 'Crack Clue' },
      automationLevel: 'semi_automated',
    }),
    shrine: mechanic({
      id: 'shrine',
      name: 'Shrine',
      kind: 'subtype',
      setCodes: ['CHK', 'NEO', 'TLA'],
      rulesText: 'Shrine is an enchantment subtype with cross-card counting patterns.',
      eventHooks: ['manual'],
      parameters: { subtype: 'Shrine' },
      ui: { badge: 'Shrine' },
      automationLevel: 'metadata_only',
    }),
    sneak: mechanic({
      id: 'sneak',
      name: 'Sneak',
      kind: 'cost',
      setCodes: ['DSK'],
      rulesText: 'Alternative-cost metadata hook.',
      engineHandler: 'sneak.alternativeCost.v1',
      eventHooks: ['onCast'],
      parameters: { alternativeCost: true },
      ui: { reminder: 'Prompt for sneak cost and delayed instruction.' },
      automationLevel: 'manual_prompt',
    }),
    disappear: mechanic({
      id: 'disappear',
      name: 'Disappear',
      kind: 'action',
      setCodes: ['TLA'],
      rulesText: 'Metadata-only placeholder for disappear-style exile/leave tracking.',
      eventHooks: ['manual'],
      parameters: {},
      ui: { reminder: 'Resolve disappear text manually.' },
      automationLevel: 'manual_prompt',
    }),
    alliance: mechanic({
      id: 'alliance',
      name: 'Alliance',
      kind: 'ability_word',
      setCodes: ['SNC'],
      rulesText: 'Ability word for triggers that care about another creature entering under your control.',
      eventHooks: ['onEnterBattlefield'],
      parameters: { triggerPattern: 'anotherCreatureEnters' },
      ui: { reminder: 'Check alliance when another creature enters.' },
      automationLevel: 'hint_only',
    }),
    'mutagen-token': mechanic({
      id: 'mutagen-token',
      name: 'Mutagen token',
      kind: 'token',
      setCodes: ['WHO'],
      rulesText: 'Metadata placeholder for Mutagen token creation and token identity.',
      eventHooks: ['manual'],
      parameters: { tokenId: 'mutagen' },
      ui: { badge: 'Mutagen' },
      automationLevel: 'metadata_only',
    }),
    classes: mechanic({
      id: 'classes',
      name: 'Classes',
      kind: 'card_type',
      setCodes: ['AFR'],
      rulesText: 'Class enchantments track a class level as card state, not counters; level abilities unlock at that level or below.',
      eventHooks: ['onActivateAbility'],
      parameters: { activateAsSorcery: true, levelIsCounter: false },
      ui: { reminder: 'Classes track level as card state, not counters. Level up at sorcery speed.' },
      automationLevel: 'hint_only',
    }),
    'partner-character-select': mechanic({
      id: 'partner-character-select',
      name: 'Partner--Character select',
      kind: 'keyword',
      setCodes: ['WHO'],
      rulesText: 'Commander deck-building metadata for paired legendary characters.',
      eventHooks: ['manual'],
      parameters: { commanderPairing: true },
      ui: { reminder: 'Validate the selected partner pairing during deck checks.' },
      automationLevel: 'metadata_only',
    }),
    blight: mechanic({
      id: 'blight',
      name: 'Blight',
      kind: 'counter',
      setCodes: ['WHO'],
      rulesText: 'Metadata placeholder for blight counters or blight-like markers.',
      eventHooks: ['onCounterAdded'],
      parameters: { counterType: 'blight' },
      ui: { badge: 'Blight' },
      automationLevel: 'manual_prompt',
    }),
    vivid: mechanic({
      id: 'vivid',
      name: 'Vivid',
      kind: 'counter',
      setCodes: ['LCC'],
      rulesText: 'Metadata placeholder for vivid counters.',
      eventHooks: ['onCounterAdded'],
      parameters: { counterType: 'vivid' },
      ui: { badge: 'Vivid' },
      automationLevel: 'metadata_only',
    }),
    changeling: mechanic({
      id: 'changeling',
      name: 'Changeling',
      kind: 'keyword',
      setCodes: ['LRW', 'KHM'],
      rulesText: 'This object is every creature type.',
      eventHooks: ['manual'],
      parameters: { allCreatureTypes: true },
      ui: { reminder: 'Treat as every creature type.' },
      automationLevel: 'hint_only',
    }),
    kindred: mechanic({
      id: 'kindred',
      name: 'Kindred',
      kind: 'card_type',
      setCodes: ['MH3'],
      rulesText: 'Kindred is the updated card type for noncreature cards with creature types.',
      eventHooks: ['manual'],
      parameters: { cardType: 'Kindred' },
      ui: { badge: 'Kindred' },
      automationLevel: 'metadata_only',
    }),
    station: mechanic({
      id: 'station',
      name: 'Station',
      kind: 'action',
      setCodes: ['EOE'],
      rulesText: 'Tap creatures to add charge counters to a station object.',
      engineHandler: 'station.chargeCounters.v1',
      eventHooks: ['onActivateAbility', 'onCounterAdded'],
      parameters: { counterType: 'charge' },
      ui: { actionLabel: 'Station', reminder: 'Tap creatures to add charge counters.' },
      automationLevel: 'manual_prompt',
    }),
    spacecraft: mechanic({
      id: 'spacecraft',
      name: 'Spacecraft',
      kind: 'card_type',
      setCodes: ['EOE'],
      rulesText: 'Metadata for Spacecraft cards and station-like interaction hints.',
      eventHooks: ['manual'],
      parameters: { subtypeOrType: 'Spacecraft' },
      ui: { badge: 'Spacecraft' },
      automationLevel: 'metadata_only',
    }),
    warp: mechanic({
      id: 'warp',
      name: 'Warp',
      kind: 'cost',
      setCodes: ['EOE'],
      rulesText: 'Alternative-cost hook with delayed object handling.',
      engineHandler: 'warp.alternativeCost.v1',
      eventHooks: ['onCast', 'onZoneChange'],
      parameters: { alternativeCost: true },
      ui: { reminder: 'Prompt for warp cost and delayed instruction.' },
      automationLevel: 'manual_prompt',
    }),
    void: mechanic({
      id: 'void',
      name: 'Void',
      kind: 'ability_word',
      setCodes: ['EOE'],
      rulesText: 'Metadata placeholder for void ability-word checks.',
      eventHooks: ['manual'],
      parameters: {},
      ui: { reminder: 'Check the card-specific void condition manually.' },
      automationLevel: 'manual_prompt',
    }),
    'lander-token': mechanic({
      id: 'lander-token',
      name: 'Lander token',
      kind: 'token',
      setCodes: ['EOE'],
      rulesText: 'Metadata placeholder for Lander token identity.',
      eventHooks: ['manual'],
      parameters: { tokenId: 'lander' },
      ui: { badge: 'Lander' },
      automationLevel: 'metadata_only',
    }),
    connive: mechanic({
      id: 'connive',
      name: 'Connive',
      kind: 'action',
      setCodes: ['SNC'],
      rulesText: 'Draw a card, discard a card, then put a +1/+1 counter on this creature if a nonland card was discarded.',
      engineHandler: 'connive.drawDiscardCounter.v1',
      eventHooks: ['onActivateAbility'],
      parameters: { draw: 1, discard: 1, counterType: '+1/+1' },
      ui: { actionLabel: 'Connive', reminder: 'Draw, discard, then add a counter if nonland was discarded.' },
      automationLevel: 'manual_prompt',
    }),
    'transforming-modal-dfcs': mechanic({
      id: 'transforming-modal-dfcs',
      name: 'Transforming modal DFCs',
      kind: 'card_frame',
      setCodes: ['MOM', 'TLA'],
      rulesText: 'Metadata for modal double-faced cards that may transform or enter as chosen faces.',
      eventHooks: ['manual'],
      parameters: { doubleFaced: true, modal: true },
      ui: { reminder: 'Use the face-selection/transform controls for this modal DFC.' },
      automationLevel: 'hint_only',
    }),
    worthy: mechanic({
      id: 'worthy',
      name: 'Worthy',
      kind: 'ability_word',
      setCodes: ['TLA'],
      rulesText: 'Metadata placeholder for card-specific worthy conditions.',
      eventHooks: ['manual'],
      parameters: {},
      ui: { reminder: 'Check the card-specific worthy condition manually.' },
      automationLevel: 'manual_prompt',
    }),
  },
  tokens: {
    clue: token({
      id: 'clue',
      name: 'Clue',
      setCodes: ['SOI', 'MKM', 'TLA'],
      rulesText: 'Colorless Clue artifact token with "{2}, Sacrifice this artifact: Draw a card."',
      ui: { shortLabel: 'Clue', actionLabel: 'Crack Clue' },
    }),
    mutagen: token({
      id: 'mutagen',
      name: 'Mutagen',
      setCodes: ['WHO'],
      rulesText: 'Mutagen token metadata placeholder.',
      ui: { badge: 'Mutagen' },
    }),
    lander: token({
      id: 'lander',
      name: 'Lander',
      setCodes: ['EOE'],
      rulesText: 'Lander token metadata placeholder.',
      ui: { badge: 'Lander' },
    }),
  },
  interactionHints: {
    'unknown-mechanic': {
      id: 'unknown-mechanic',
      text: 'This mechanic is not locally automated. Show the card text and ask players to resolve it manually.',
      severity: 'manual',
      updatedAt: now,
    },
  },
  cardOverrides: {},
};
